name: Bug report
description: File a bug report to help us improve
labels: [bug]
title: "bug: <short description>"
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checklist
      options:
        - label: I have searched the existing issues and discussions
          required: true
        - label: I am using the latest version
          required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: What version/commit are you using? (e.g., 0.2.0 or commit SHA)
      placeholder: 0.2.0
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Tell us what you expected to happen, and what actually happened.
      placeholder: A clear and concise description of the bug.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
      description: Provide a minimal, complete, and verifiable example or list of steps.
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs and stack traces
      description: Paste any relevant logs or stack traces. Use backticks to format code or logs.
      render: shell
    validations:
      required: false
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your OS, Node.js, package manager, browser (if applicable), etc.
      placeholder: |
        - OS: macOS 14.5
        - Node: 20.x
        - Package manager: npm 10.x
        - Browser: Chrome 129
    validations:
      required: false
  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: Add any other context about the problem here, including screenshots if useful.
    validations:
      required: false
